<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StripePayment\Form;

use StripePayment\StripePayment;
use StripePayment\Form\Base\StripePaymentConfigForm as BaseStripePaymentConfigForm;

/**
 * Class StripePaymentConfigForm
 * @package StripePayment\Form\Base
 */
class StripePaymentConfigForm extends BaseStripePaymentConfigForm
{
    public function getTranslationKeys()
    {
        return array(
            "enabled" => $this->translator->trans("Activated ?", [], StripePayment::MESSAGE_DOMAIN),
            "secret_key" => $this->translator->trans("Your secret key", [], StripePayment::MESSAGE_DOMAIN),
            "publishable_key" => $this->translator->trans("Your publishable key (test or live)", [], StripePayment::MESSAGE_DOMAIN),
            "help.enabled" => $this->translator->trans("Do you want to activate Stripe Payment", [], StripePayment::MESSAGE_DOMAIN),
            "help.secret_key" => $this->translator->trans("You can see all your keys in your <a target=\"_blank\" href=\"https://dashboard.stripe.com/\">Stripe dashboard</a>. Also note that you can place your test or your live API keys", [], StripePayment::MESSAGE_DOMAIN),
        );
    }
}
