<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace StripePayment\Controller;

use StripePayment\Controller\Base\StripePaymentConfigController as BaseStripePaymentConfigController;

/**
 * Class StripePaymentConfigController
 * @package StripePayment\Controller
 */
class StripePaymentConfigController extends BaseStripePaymentConfigController
{
}
